version: '3.8'

services:
  mariadb:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
    restart: always

  app:
    image: node:18
    working_dir: /usr/src/app
    volumes:
      - ./:/usr/src/app
    command: node index.js
    depends_on:
      - mariadb
    environment:
      DB_HOST: mariadb
      DB_USER: root
      DB_PASSWORD: 123456
    ports:
      - "3000:3000"

volumes:
  mariadb_data:
